### ISSUE TITLE
Docs: Mention alternative package for generating Markdown tables

### ISSUE THREAD

**Issue by montanaflynn** [JoshuaKGoldberg/text-table-fast#7]
### Bug Report Checklist

- [X] I have pulled the latest `main` branch of the repository.
- [X] I have [searched for related issues](https://github.com/JoshuaKGoldberg/text-table-fast/issues?q=is%3Aissue) and found none that matched my issue.

### Overview

`horizontalSeparator` gets very close to markdown tables, if it could also put a separator under the first row it would be a fully compliant markdown table. I like to print tables that can be copied and pasted into issues or markdown files.

Without header separator:

```
abc  | abcd |  abc
1234 |  12  | 1234
```

abc  | abcd |  abc
1234 |  12  | 1234

With header separator:

```
abc  | abcd |  abc
---- | ---- | ----
1234 |  12  | 1234
```

abc  | abcd |  abc
---- | ---- | ----
1234 |  12  | 1234

**Comment by JoshuaKGoldberg** [comment]
Hey thanks for suggesting this @montanaflynn! It didn't occur to me just how close this package is to Markdown tables, good spot.

But, actually getting compliant Markdown tables would be a bit more involved than this. There are a lot of edge cases around cell data sanitization that'd have to be accounted for. For example, cells with special characters such as `'|'` and `'\n'`:

```js
import { textTable } from "text-table";

console.log(
	textTable(
		[["a", "|", "\n", "z"]],
		{ horizontalSeparator: "|" },
	),
);
```

```plaintext
a|||
|z
```

This package is _very_ small right now. Adding in handling for those and other encoding things would increase its size a lot and hurt runtime performance.

I think it'd make sense to instead link to a dedicated package for a markdown table in the README.md. Adding docs would help explain that this package is just for very basic + quick table layout, not full Markdown / GFM workability. A quick Google/npm search shows https://www.npmjs.com/package/markdown-table - which actually mentions the original `text-table` at the bottom of its README.md!
